# Comparison Operators

In [1]:
import numpy as np
np_length = np.array([2.7, 3.4, 4.7, 6.6, 7.8])
np_breath = np.array([3.7, 1.4, 2.7, 3.6, 1.8])
np_height = np.array([1.7, 2.4, 1.7, 0.6, 1.8])
vol_cuboid = np_length * np_breath * np_height
vol_cuboid

array([16.983, 11.424, 21.573, 14.256, 25.272])

Show the vol_cuboid which are greater than 15

In [2]:
## Start code here
vol_cuboid>15

## End here

array([ True, False,  True, False,  True])

## Numeric & Variable Comparison

Using comparison operators show:

Q1. If 10.5 is greater thean 10

Q2. If 10.5 is greater than equal to 10.5

Q3. If 20 is equal to 20.1

Q4. If Ansh is greater than Anshu

Q5. If Monkey is greater than 5

In [3]:
# 1
## Start code here
10.5>10

## End here

True

In [4]:
# 2
## Start code here
10.5>=10.5
## End here

True

In [5]:
# 3
## Start code here
20==20.1
## End here

False

In [7]:
# 4
## Start code here
Ansh>Anshu
## End here

NameError: name 'Ansh' is not defined

We can not compare between strings.

In [8]:
# 5
## Start code here
Monkey>5
## End here

NameError: name 'Monkey' is not defined

We can not compare strings with integers.

## Boolean Operators

1. and
2. or
3. not

Q1. Use and operator to check if x is greater than 2 and less than 10

Q2. Use or operator to check if x is grater than 3 and less than 10

Q3. Use not operator to check if x is greater than 5 and less than 8

In [9]:
# 1
## Start code here
x=5
print(x > 2 and x < 10)

## End here

True


In [10]:
# 2
## Start code here
x=5
print(x > 3 or x < 10)

## End here

True


In [11]:
# 3
## Start code here
x=5
print(not(x > 5 and x < 10))

## End here

True


## Numpy

1. logical_and()
2. logical_or()
3. logical_not()

Q1. Use the logical_and operator to check if vol_cuboid is greater than 11 and less than 20

Q2. Use the logical_or operator to check if vol_cuboid is greater than 11 and less than 20

Q3. Use the logical_not operator to check if vol_cuboid is greater than 11 and less than 20

In [12]:
# 1
## Start code here
x=vol_cuboid
np.logical_and(x >11 , x < 20)


## End here

array([ True,  True, False,  True, False])

In [13]:
# 2
## Start code here
x=vol_cuboid
np.logical_or(x >11 , x < 20)

## End here

array([ True,  True,  True,  True,  True])

In [14]:
# 3
## Start code here
x=vol_cuboid
np.logical_not(x >11 , x < 20)

## End here

array([False, False, False, False, False])

## if , elif , else

In [15]:
a = 100
b = 10

Q1. Use if condition statment to check if a is greater than b and print the greatest number.

Q2. Use else condition statment to check if b is greater or less than a and print the greatest number.

Q3. Use elif condition statment to check if b is greater , less than or equal to a and print the greatest number.

In [16]:
# 1
## Start code here
if a>b:
    print("The greatest number is",a)

## End here

The greatest number is 100


In [17]:
# 2
## Start code here
if b>a:
   print("The greatest number is",b);
else:
   print("The greatest number is",a)

## End here

The greatest number is 100


In [18]:
# 3
## Start code here
if b>a:
   print("The greatest number is",b);
elif b<a:
   print("The greatest number is",a)


## End here

The greatest number is 100


## Filtering pandas Dataframes

In [19]:
df = {
    "Name": ["aparna", "pankaj", "sudhir", "Geeku", "Chiku", "Jeniffer"], 
    "Degree": ["Bsc", "Engineering", "Law", "MBBS", "Phd", "Nursing"],
    "College": ["VIT", "IIT", "KIIT", "AIMS", "IIIT", "APPOLO"],
    "Score": [90, 70, 80, 98, 76, 89]} 

import pandas as pd
dataframe = pd.DataFrame(df)
dataframe

Name       Degree College  Score
0    aparna          Bsc     VIT     90
1    pankaj  Engineering     IIT     70
2    sudhir          Law    KIIT     80
3     Geeku         MBBS    AIMS     98
4     Chiku          Phd    IIIT     76
5  Jeniffer      Nursing  APPOLO     89

Q1. Access the Score column

Q2. Use comparison operator to show which students has score greater than 80

Q3. Use logical_and operator to see scores greater than 75 and less than 90

In [20]:
# 1
## Start code here

print(dataframe[['Score']])

## End here

   Score
0     90
1     70
2     80
3     98
4     76
5     89


In [21]:
# 2
## Start code here

print(dataframe[(dataframe['Score'] > 80)])

## End here

       Name   Degree College  Score
0    aparna      Bsc     VIT     90
3     Geeku     MBBS    AIMS     98
5  Jeniffer  Nursing  APPOLO     89


In [22]:
# 3
## Start code here


print(dataframe[np.logical_and(dataframe['Score'] >75 , dataframe['Score'] < 90)])


## End here

       Name   Degree College  Score
2    sudhir      Law    KIIT     80
4     Chiku      Phd    IIIT     76
5  Jeniffer  Nursing  APPOLO     89
